### ISSUE TITLE
Datenfeld zu Entities hinzufügen, ob sie gerade als Favorit makiert sind

### ISSUE THREAD

**Issue by kiesthardt** [BachelorProjektAI-HSFulda/megaApp#104]
- Einführung von Rückgabewerten beim favorisieren und entfavorisieren, damit im Frontend entsprechend korrekt makiert werden kann

**Comment by w4tsn** [comment]
Ob etwas ein Favorit ist kann man glaube ich über den Favorite Service in Erfahrung bringen. Dieser Speichert die Favoriten und kann die deshalb auch sagen ob eine bestimmte Entity ein Favorit ist.

Dokumentation zu diesem Service wäre vermutlich noch sinnvoll.
