### ISSUE TITLE
UI entwerfen

### ISSUE THREAD

**Issue by kiesthardt** [BachelorProjektAI-HSFulda/megaApp#12]

**Comment by w4tsn** [comment]
Was war den jetzt der finale Entwurf bisher? Es gab doch drei Stück? Wurde einer davon ausgewählt oder sollte es hier eine Mischung aus mehreren werden?

Wie wollen wir mit der UI für Desktop verfahren? Wollen wir hier ein zweites Team bauen oder denkt ihr wir haben im Anschluss an die Mobile UI noch genug Zeit wenn ihr das auch übernehmt?
