### ISSUE TITLE
Meteor Evaluation

### ISSUE THREAD

**Issue by FelixB92** [BachelorProjektAI-HSFulda/megaApp#14]

**Comment by Azmodis** [comment]
Meteor vereint alle möglichen Funktionen aus Frameworks und ermöglicht somit einen gleichzeitigen Zugriff auf Client- und Serverseitiges sowie Datenbanken.  Ich persönlich erachte Meteor als Overkill und Zusatzballast, da unser Stack eigentlich bereits alles abdeckt und wir einige Anteile von Meteor auch nicht bräuchten. Wir sollten es aber in der Gruppe noch einmal kurz ansprechen.
