### ISSUE TITLE
Metadaten aus Objekt abrufen und anzeigen

### ISSUE THREAD

**Issue by Azmodis** [BachelorProjektAI-HSFulda/megaApp#33]

**Comment by w4tsn** [comment]
Was genau ist mit diesem Issue gemeint? Könnte es ein Duplicate von #49 sein?

**Comment by Azmodis** [comment]
Teilweise. Hier geht es eher um die spätere Aufbereitung, wie sie der Nutzer dann auch zu Gesicht bekommen wird. #49 beschäftigt sich eher mit den Dingen, die zur Funktionalität gehören und die Objektstruktur betreffen, nicht mit der Präsentation.
Insofern ist die "Konstruktion einer Schnittstelle" vielleicht in dem Fall von mir etwas zu allgemein betitelt.
