### ISSUE TITLE
Erzeugen von Objekten in api_service einbinden

### ISSUE THREAD

**Issue by Azmodis** [BachelorProjektAI-HSFulda/megaApp#43]
Im api.service müssen die von der Synacta API erhaltenen JSON-Objekte mit einem Interface für die lokale Weiterverarbeitung ausgestattet werden. 

Diese Interfaces können entweder 

1. durch das Konzept interface verfügbar gemacht werden 
2. oder aber durch das Implementieren einer eigenen Objekt-Struktur und das anschließende Übersetzen von JSON zu Objekt.

**Comment by w4tsn** [comment]
Duplicate of #32

**Comment by Azmodis** [comment]
Teilweise. Dieses Issue behandelt das Einbinden unserer ausgelagerten Objekterzeugung in den Request-Service, während #32 eben die Objekterzeugung an sich als Sammlung von Funktionen beinhaltet. Ob sich das jetzt so entwickelt, dass sich das ganze irgendwann doch komplett in api_service zusammenschließt und dort alle Aufgaben übernommen werden, hängt unter Anderem von Felix' Implementierung ab und lässt sich so zu diesem Zeitpunkt noch nicht festlegen.

Habe #32 daher umbenannt, um's klarer zu gestalten.

**Comment by w4tsn** [comment]
Die Aktuelle Struktur sieht vor die Objekt-Erzeugung direkt im API-Service abzuhandeln und von dort aus bereits fertige Objekte zurückzugeben bzw. auch mit Objekten zu arbeiten. Dies spart einen zusätzlichen Übersetzung Layer und ist sinnvoll, da sich die API nur selten Ändern sollte und die Objekte entsprechend ebenfalls.
