### ISSUE TITLE
Refactoring der Objektklassen und -strukturen

### ISSUE THREAD

**Issue by Azmodis** [BachelorProjektAI-HSFulda/megaApp#47]

**Comment by w4tsn** [comment]
Recherche über Interfaces und Duck-Typing in TS abgeschlossen. Prinzipiell sehr schön: man holt sich das JSON-Objekt und weißt es einer Variablen vom Typ eines Interfaces zu. Damit kann man dann Typ-Sicher die Variable behandeln. Man muss nur vorher sicherstellen, dass das Objekt das Interface auch erfüllt.

Problem bei der Synacta-Schnittstelle: Durch keys wie @odata kann eine einfache Version des Duck-Typings nicht funktionieren. Die entsprechenden keys mit Sonderzeichen werden vom Compiler nicht zu JavaScript übersetzt.

## Lösungsansätze

1. Diese key:value Paare nicht in das Interface aufnehmen und sie bei Bedarf Manuell mit var[key]-Notation abfragen. (Da es per Interface eingeordnet ist, kann hier zumindest darüber identifiziert werden)
2. Nach [diesem Guide](http://cloudmark.github.io/Json-Mapping/) einen deserializer implementieren/einbinden, welcher generisch Json-Objekte zu JS-Objekten konvertiert.

Die erste Variante ist deutlich schneller und wird auch erstmal implementiert werden. Die zweite erlaubt IntelliSense und mehr Type-Safety. Bei Bedarf kann diese noch implementiert werden.

**Comment by w4tsn** [comment]
Es gibt jetzt durch den import

`import { IBaseEntityFrame, IEntity, IContainer, IDocument } from 'core/synacta/api.objects'`

eine Reihe von Interfaces welche einige Felder der Json-Objekte in Typescript abbilden.

Dabei steht **IBaseEntityFrame** für das Objekt, welches bei einem API-Call zurückgegeben wird. Es enthält die Antwort-Objekte im Value-Array.

**IEntity** ist ein Super-Interface welches manche Felder enthält, die sowohl container als auch document enthalten.

Ein JSON-Objekt kann einfach einem dieser Typen zugewiesen indem:

```
let x: IContainer;
x = jsonObject; // which is a container obviously
x.ID => magic!
```

**Comment by Azmodis** [comment]
Ich weiß nicht, die Keys in der JSON sind ja dieses "@odataXYZ" et cetera, oder? Ich habe jedenfalls in #49 schon damit angefangen, die ganzen Werte dort zu interpertieren, Parameter dafür zu benennen und mir zu überlegen, wie man damit allgemein dann umgehen kann, weil die ja doch sehr nützlich sind.

**Comment by w4tsn** [comment]
Dann bau es erstmal fertig. Wir schauen dann weiter :)
