### ISSUE TITLE
api.service.ts überarbeiten

### ISSUE THREAD

**Issue by FelixB92** [BachelorProjektAI-HSFulda/megaApp#48]

**Comment by FelixB92** [comment]
get() auf private
JSON's an createObject übergeben und Interface erhalten und weitergeben.

**Comment by w4tsn** [comment]
Improvements in Commits:

f112a0549dcdb013047bd5e0db666b9144cee401, 14f0289b937615708418d4336d36e361bcff485e, 5e7763a95b473df1099f24972d8b5c0e1ed982c3, a836672cda07af84583410dfd3856afb99a24f28, a042c8ee466960f61d2e1404654d7f9d4b086a68, 65ae76b916ebd039ba3e9eb5b21cfc98e0a297f0, 9efb257ded6415b92236f21acff12f4b4d5a451e, 60d2274c17d1f0dacc88c733d299c7cec15c04e4

**Comment by w4tsn** [comment]
Aktuell sollte der Service eine Version 1 haben. Das Issue ist damit erledigt. Weitere Änderungen/Features sind dann neue, bzw. zusätzliche Dinge.
