### ISSUE TITLE
Synacta-Link-Parameter interpretieren und in Klassen schreiben

### ISSUE THREAD

**Issue by Azmodis** [BachelorProjektAI-HSFulda/megaApp#49]

**Comment by w4tsn** [comment]
Siehe Type-Assertion
https://basarat.gitbooks.io/typescript/content/docs/types/type-assertion.html
und
http://cloudmark.github.io/Json-Mapping/

Der letzte Beitrag ist vor allem Interessant, weil es da wirklich um eigene Klassen geht die aber dynamisch mit Json-Inhalten befüllt werden. Sehr elegante Lösung wie ich finde. Habe da auch schon was aber noch nicht fertig.
