### ISSUE TITLE
Synacta API scheint Sonntags frei zu machen

### ISSUE THREAD

**Issue by w4tsn** [BachelorProjektAI-HSFulda/megaApp#60]
Die API gibt wieder nur 500 zurück.

**Comment by Azmodis** [comment]
Nur 500er? Werden wir jetzt doch mit dem Projekt reich?! :D

**Comment by KlSteigerwald** [comment]
Das lag glaube ich am Server denn vom Samstag nachmittag bis Montags morgens ging auch https://synacta.agile-is.de/_api/index.html#/
