### ISSUE TITLE
Abfrage von Properties in Entities ermöglichen

### ISSUE THREAD

**Issue by FelixB92** [BachelorProjektAI-HSFulda/megaApp#62]
Properties ist also "any" definiert und dadurch ist arbeiten mit Werten innerhalb der Properties erschwert.

=> "any" passend abändern, damit Arbeit mit Werten innerhalb von Properties ermöglicht wird

**Comment by w4tsn** [comment]
Dieses Verhalten ist beabsichtigt, da die Properties dynamische Daten sind und diese sich nach ermessen der Nutzer beliebig ändern kann.

Als Alternative könnten fürs erste manche Wiederkehrenden Felder als Interface realisiert werden und die Json-Daten dann über ein Interface ge-Duck-Typed werden.
