### ISSUE TITLE
Development-Branch aktualisieren

### ISSUE THREAD

**Issue by Azmodis** [BachelorProjektAI-HSFulda/megaApp#92]
Da Electron jetzt an sich funktionieren könnte, wäre es gut, wenn jeder seinen Stand in den Development-Branch merget, damit ich mit der aktuellen Version weiterarbeiten kann.

Dazu
1. development synchen
2. pull request von eurem Branch zu development stellen
3. wieder wie gewohnt im Branch eurer Wahl weiterarbeiten

**Comment by w4tsn** [comment]
Der Branch wurde auf den aktuellsten Stand gebracht.
